# Generated by Django 6.1.1 on 2026-09-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.DateField(blank=True, null=True, verbose_name='Год реализации'),
        ),
    ]
