# Generated by Django 6.1 on 2026-09-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
